# Generated by Django 6.0 on 2025-12-14 14:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SDGProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sdg_goal', models.IntegerField(choices=[(1, 'No Poverty'), (2, 'Zero Hunger'), (3, 'Good Health and Well-being'), (4, 'Quality Education'), (5, 'Gender Equality'), (6, 'Clean Water and Sanitation'), (7, 'Affordable and Clean Energy'), (8, 'Decent Work and Economic Growth'), (9, 'Industry, Innovation, and Infrastructure'), (10, 'Reduced Inequality'), (11, 'Sustainable Cities and Communities'), (12, 'Responsible Consumption and Production'), (13, 'Climate Action'), (14, 'Life Below Water'), (15, 'Life on Land'), (16, 'Peace, Justice, and Strong Institutions'), (17, 'Partnerships for the Goals')], default=1)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phone_number', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdg_platform.sdgproject')),
            ],
        ),
    ]
