# Generated by Django 6.0 on 2025-12-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdg_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdgproject',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
